# Generated by Django 5.1.6 on 2025-12-09 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('tipo_combustivel', models.CharField(choices=[('GAS', 'Gasolina'), ('ETA', 'Etanol'), ('DIE', 'Diesel'), ('FLEX', 'Flex'), ('ELE', 'Elétrico'), ('HIB', 'Híbrido')], max_length=5)),
                ('portas', models.PositiveIntegerField(default=4)),
                ('motor', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='veiculos/')),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='veiculos/')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.veiculo')),
            ],
        ),
    ]
