# Generated by Django 5.1.6 on 2025-12-09 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cambio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='final_placa',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='potencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quilometragem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='unico_dono',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/imagens'),
        ),
        migrations.AlterField(
            model_name='veiculoimagem',
            name='imagem',
            field=models.ImageField(upload_to='veiculos/imagens'),
        ),
        migrations.AlterField(
            model_name='veiculoimagem',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='catalogo.veiculo'),
        ),
    ]
