# Generated by Django 5.1.6 on 2025-12-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_veiculo_cambio_veiculo_final_placa_veiculo_potencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.TextField(),
        ),
    ]
