# Generated by Django 5.2.11 on 2026-02-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=14)),
                ('veiculo_marca', models.CharField(max_length=100)),
                ('veiculo_modelo', models.CharField(max_length=100)),
                ('veiculo_ano', models.PositiveIntegerField()),
                ('veiculo_km', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
