# Generated by Django 5.2.11 on 2026-02-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='uploads/veiculos/')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='vendas.leadvenda')),
            ],
        ),
    ]
