# Generated by Django 5.2.11 on 2026-02-18 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0003_alter_veiculo_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('possui_cnh', models.BooleanField(default=False)),
                ('valor_entrada', models.CharField(max_length=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='catalogo.veiculo')),
            ],
        ),
    ]
